
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StrollHistoryCategory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StrollHistoryCategory
 * 
 */
export type StrollHistoryCategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$StrollHistoryCategoryPayload>

export type AggregateStrollHistoryCategory = {
  _count: StrollHistoryCategoryCountAggregateOutputType | null
  _min: StrollHistoryCategoryMinAggregateOutputType | null
  _max: StrollHistoryCategoryMaxAggregateOutputType | null
}

export type StrollHistoryCategoryMinAggregateOutputType = {
  strollHistoryId: string | null
  categoryId: string | null
}

export type StrollHistoryCategoryMaxAggregateOutputType = {
  strollHistoryId: string | null
  categoryId: string | null
}

export type StrollHistoryCategoryCountAggregateOutputType = {
  strollHistoryId: number
  categoryId: number
  _all: number
}


export type StrollHistoryCategoryMinAggregateInputType = {
  strollHistoryId?: true
  categoryId?: true
}

export type StrollHistoryCategoryMaxAggregateInputType = {
  strollHistoryId?: true
  categoryId?: true
}

export type StrollHistoryCategoryCountAggregateInputType = {
  strollHistoryId?: true
  categoryId?: true
  _all?: true
}

export type StrollHistoryCategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StrollHistoryCategory to aggregate.
   */
  where?: Prisma.StrollHistoryCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StrollHistoryCategories to fetch.
   */
  orderBy?: Prisma.StrollHistoryCategoryOrderByWithRelationInput | Prisma.StrollHistoryCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StrollHistoryCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StrollHistoryCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StrollHistoryCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StrollHistoryCategories
  **/
  _count?: true | StrollHistoryCategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StrollHistoryCategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StrollHistoryCategoryMaxAggregateInputType
}

export type GetStrollHistoryCategoryAggregateType<T extends StrollHistoryCategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateStrollHistoryCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStrollHistoryCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateStrollHistoryCategory[P]>
}




export type StrollHistoryCategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StrollHistoryCategoryWhereInput
  orderBy?: Prisma.StrollHistoryCategoryOrderByWithAggregationInput | Prisma.StrollHistoryCategoryOrderByWithAggregationInput[]
  by: Prisma.StrollHistoryCategoryScalarFieldEnum[] | Prisma.StrollHistoryCategoryScalarFieldEnum
  having?: Prisma.StrollHistoryCategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StrollHistoryCategoryCountAggregateInputType | true
  _min?: StrollHistoryCategoryMinAggregateInputType
  _max?: StrollHistoryCategoryMaxAggregateInputType
}

export type StrollHistoryCategoryGroupByOutputType = {
  strollHistoryId: string
  categoryId: string
  _count: StrollHistoryCategoryCountAggregateOutputType | null
  _min: StrollHistoryCategoryMinAggregateOutputType | null
  _max: StrollHistoryCategoryMaxAggregateOutputType | null
}

export type GetStrollHistoryCategoryGroupByPayload<T extends StrollHistoryCategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StrollHistoryCategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StrollHistoryCategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StrollHistoryCategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StrollHistoryCategoryGroupByOutputType[P]>
      }
    >
  >



export type StrollHistoryCategoryWhereInput = {
  AND?: Prisma.StrollHistoryCategoryWhereInput | Prisma.StrollHistoryCategoryWhereInput[]
  OR?: Prisma.StrollHistoryCategoryWhereInput[]
  NOT?: Prisma.StrollHistoryCategoryWhereInput | Prisma.StrollHistoryCategoryWhereInput[]
  strollHistoryId?: Prisma.StringFilter<"StrollHistoryCategory"> | string
  categoryId?: Prisma.StringFilter<"StrollHistoryCategory"> | string
  strollHistory?: Prisma.XOR<Prisma.StrollHistoryScalarRelationFilter, Prisma.StrollHistoryWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
}

export type StrollHistoryCategoryOrderByWithRelationInput = {
  strollHistoryId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  strollHistory?: Prisma.StrollHistoryOrderByWithRelationInput
  category?: Prisma.CategoryOrderByWithRelationInput
}

export type StrollHistoryCategoryWhereUniqueInput = Prisma.AtLeast<{
  strollHistoryId_categoryId?: Prisma.StrollHistoryCategoryStrollHistoryIdCategoryIdCompoundUniqueInput
  AND?: Prisma.StrollHistoryCategoryWhereInput | Prisma.StrollHistoryCategoryWhereInput[]
  OR?: Prisma.StrollHistoryCategoryWhereInput[]
  NOT?: Prisma.StrollHistoryCategoryWhereInput | Prisma.StrollHistoryCategoryWhereInput[]
  strollHistoryId?: Prisma.StringFilter<"StrollHistoryCategory"> | string
  categoryId?: Prisma.StringFilter<"StrollHistoryCategory"> | string
  strollHistory?: Prisma.XOR<Prisma.StrollHistoryScalarRelationFilter, Prisma.StrollHistoryWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
}, "strollHistoryId_categoryId">

export type StrollHistoryCategoryOrderByWithAggregationInput = {
  strollHistoryId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  _count?: Prisma.StrollHistoryCategoryCountOrderByAggregateInput
  _max?: Prisma.StrollHistoryCategoryMaxOrderByAggregateInput
  _min?: Prisma.StrollHistoryCategoryMinOrderByAggregateInput
}

export type StrollHistoryCategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.StrollHistoryCategoryScalarWhereWithAggregatesInput | Prisma.StrollHistoryCategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.StrollHistoryCategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StrollHistoryCategoryScalarWhereWithAggregatesInput | Prisma.StrollHistoryCategoryScalarWhereWithAggregatesInput[]
  strollHistoryId?: Prisma.StringWithAggregatesFilter<"StrollHistoryCategory"> | string
  categoryId?: Prisma.StringWithAggregatesFilter<"StrollHistoryCategory"> | string
}

export type StrollHistoryCategoryCreateInput = {
  strollHistory: Prisma.StrollHistoryCreateNestedOneWithoutCategoriesInput
  category: Prisma.CategoryCreateNestedOneWithoutStrollHistoriesInput
}

export type StrollHistoryCategoryUncheckedCreateInput = {
  strollHistoryId: string
  categoryId: string
}

export type StrollHistoryCategoryUpdateInput = {
  strollHistory?: Prisma.StrollHistoryUpdateOneRequiredWithoutCategoriesNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutStrollHistoriesNestedInput
}

export type StrollHistoryCategoryUncheckedUpdateInput = {
  strollHistoryId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StrollHistoryCategoryCreateManyInput = {
  strollHistoryId: string
  categoryId: string
}

export type StrollHistoryCategoryUpdateManyMutationInput = {

}

export type StrollHistoryCategoryUncheckedUpdateManyInput = {
  strollHistoryId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StrollHistoryCategoryListRelationFilter = {
  every?: Prisma.StrollHistoryCategoryWhereInput
  some?: Prisma.StrollHistoryCategoryWhereInput
  none?: Prisma.StrollHistoryCategoryWhereInput
}

export type StrollHistoryCategoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StrollHistoryCategoryStrollHistoryIdCategoryIdCompoundUniqueInput = {
  strollHistoryId: string
  categoryId: string
}

export type StrollHistoryCategoryCountOrderByAggregateInput = {
  strollHistoryId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type StrollHistoryCategoryMaxOrderByAggregateInput = {
  strollHistoryId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type StrollHistoryCategoryMinOrderByAggregateInput = {
  strollHistoryId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type StrollHistoryCategoryCreateNestedManyWithoutStrollHistoryInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput> | Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput[] | Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput[]
  connectOrCreate?: Prisma.StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput[]
  createMany?: Prisma.StrollHistoryCategoryCreateManyStrollHistoryInputEnvelope
  connect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
}

export type StrollHistoryCategoryUncheckedCreateNestedManyWithoutStrollHistoryInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput> | Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput[] | Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput[]
  connectOrCreate?: Prisma.StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput[]
  createMany?: Prisma.StrollHistoryCategoryCreateManyStrollHistoryInputEnvelope
  connect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
}

export type StrollHistoryCategoryUpdateManyWithoutStrollHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput> | Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput[] | Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput[]
  connectOrCreate?: Prisma.StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput[]
  upsert?: Prisma.StrollHistoryCategoryUpsertWithWhereUniqueWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryUpsertWithWhereUniqueWithoutStrollHistoryInput[]
  createMany?: Prisma.StrollHistoryCategoryCreateManyStrollHistoryInputEnvelope
  set?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  disconnect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  delete?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  connect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  update?: Prisma.StrollHistoryCategoryUpdateWithWhereUniqueWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryUpdateWithWhereUniqueWithoutStrollHistoryInput[]
  updateMany?: Prisma.StrollHistoryCategoryUpdateManyWithWhereWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryUpdateManyWithWhereWithoutStrollHistoryInput[]
  deleteMany?: Prisma.StrollHistoryCategoryScalarWhereInput | Prisma.StrollHistoryCategoryScalarWhereInput[]
}

export type StrollHistoryCategoryUncheckedUpdateManyWithoutStrollHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput> | Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput[] | Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput[]
  connectOrCreate?: Prisma.StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput[]
  upsert?: Prisma.StrollHistoryCategoryUpsertWithWhereUniqueWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryUpsertWithWhereUniqueWithoutStrollHistoryInput[]
  createMany?: Prisma.StrollHistoryCategoryCreateManyStrollHistoryInputEnvelope
  set?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  disconnect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  delete?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  connect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  update?: Prisma.StrollHistoryCategoryUpdateWithWhereUniqueWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryUpdateWithWhereUniqueWithoutStrollHistoryInput[]
  updateMany?: Prisma.StrollHistoryCategoryUpdateManyWithWhereWithoutStrollHistoryInput | Prisma.StrollHistoryCategoryUpdateManyWithWhereWithoutStrollHistoryInput[]
  deleteMany?: Prisma.StrollHistoryCategoryScalarWhereInput | Prisma.StrollHistoryCategoryScalarWhereInput[]
}

export type StrollHistoryCategoryCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutCategoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput> | Prisma.StrollHistoryCategoryCreateWithoutCategoryInput[] | Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.StrollHistoryCategoryCreateOrConnectWithoutCategoryInput | Prisma.StrollHistoryCategoryCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.StrollHistoryCategoryCreateManyCategoryInputEnvelope
  connect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
}

export type StrollHistoryCategoryUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutCategoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput> | Prisma.StrollHistoryCategoryCreateWithoutCategoryInput[] | Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.StrollHistoryCategoryCreateOrConnectWithoutCategoryInput | Prisma.StrollHistoryCategoryCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.StrollHistoryCategoryCreateManyCategoryInputEnvelope
  connect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
}

export type StrollHistoryCategoryUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutCategoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput> | Prisma.StrollHistoryCategoryCreateWithoutCategoryInput[] | Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.StrollHistoryCategoryCreateOrConnectWithoutCategoryInput | Prisma.StrollHistoryCategoryCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.StrollHistoryCategoryUpsertWithWhereUniqueWithoutCategoryInput | Prisma.StrollHistoryCategoryUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.StrollHistoryCategoryCreateManyCategoryInputEnvelope
  set?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  disconnect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  delete?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  connect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  update?: Prisma.StrollHistoryCategoryUpdateWithWhereUniqueWithoutCategoryInput | Prisma.StrollHistoryCategoryUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.StrollHistoryCategoryUpdateManyWithWhereWithoutCategoryInput | Prisma.StrollHistoryCategoryUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.StrollHistoryCategoryScalarWhereInput | Prisma.StrollHistoryCategoryScalarWhereInput[]
}

export type StrollHistoryCategoryUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutCategoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput> | Prisma.StrollHistoryCategoryCreateWithoutCategoryInput[] | Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.StrollHistoryCategoryCreateOrConnectWithoutCategoryInput | Prisma.StrollHistoryCategoryCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.StrollHistoryCategoryUpsertWithWhereUniqueWithoutCategoryInput | Prisma.StrollHistoryCategoryUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.StrollHistoryCategoryCreateManyCategoryInputEnvelope
  set?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  disconnect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  delete?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  connect?: Prisma.StrollHistoryCategoryWhereUniqueInput | Prisma.StrollHistoryCategoryWhereUniqueInput[]
  update?: Prisma.StrollHistoryCategoryUpdateWithWhereUniqueWithoutCategoryInput | Prisma.StrollHistoryCategoryUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.StrollHistoryCategoryUpdateManyWithWhereWithoutCategoryInput | Prisma.StrollHistoryCategoryUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.StrollHistoryCategoryScalarWhereInput | Prisma.StrollHistoryCategoryScalarWhereInput[]
}

export type StrollHistoryCategoryCreateWithoutStrollHistoryInput = {
  category: Prisma.CategoryCreateNestedOneWithoutStrollHistoriesInput
}

export type StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput = {
  categoryId: string
}

export type StrollHistoryCategoryCreateOrConnectWithoutStrollHistoryInput = {
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput>
}

export type StrollHistoryCategoryCreateManyStrollHistoryInputEnvelope = {
  data: Prisma.StrollHistoryCategoryCreateManyStrollHistoryInput | Prisma.StrollHistoryCategoryCreateManyStrollHistoryInput[]
  skipDuplicates?: boolean
}

export type StrollHistoryCategoryUpsertWithWhereUniqueWithoutStrollHistoryInput = {
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
  update: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateWithoutStrollHistoryInput, Prisma.StrollHistoryCategoryUncheckedUpdateWithoutStrollHistoryInput>
  create: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutStrollHistoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutStrollHistoryInput>
}

export type StrollHistoryCategoryUpdateWithWhereUniqueWithoutStrollHistoryInput = {
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
  data: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateWithoutStrollHistoryInput, Prisma.StrollHistoryCategoryUncheckedUpdateWithoutStrollHistoryInput>
}

export type StrollHistoryCategoryUpdateManyWithWhereWithoutStrollHistoryInput = {
  where: Prisma.StrollHistoryCategoryScalarWhereInput
  data: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateManyMutationInput, Prisma.StrollHistoryCategoryUncheckedUpdateManyWithoutStrollHistoryInput>
}

export type StrollHistoryCategoryScalarWhereInput = {
  AND?: Prisma.StrollHistoryCategoryScalarWhereInput | Prisma.StrollHistoryCategoryScalarWhereInput[]
  OR?: Prisma.StrollHistoryCategoryScalarWhereInput[]
  NOT?: Prisma.StrollHistoryCategoryScalarWhereInput | Prisma.StrollHistoryCategoryScalarWhereInput[]
  strollHistoryId?: Prisma.StringFilter<"StrollHistoryCategory"> | string
  categoryId?: Prisma.StringFilter<"StrollHistoryCategory"> | string
}

export type StrollHistoryCategoryCreateWithoutCategoryInput = {
  strollHistory: Prisma.StrollHistoryCreateNestedOneWithoutCategoriesInput
}

export type StrollHistoryCategoryUncheckedCreateWithoutCategoryInput = {
  strollHistoryId: string
}

export type StrollHistoryCategoryCreateOrConnectWithoutCategoryInput = {
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutCategoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput>
}

export type StrollHistoryCategoryCreateManyCategoryInputEnvelope = {
  data: Prisma.StrollHistoryCategoryCreateManyCategoryInput | Prisma.StrollHistoryCategoryCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type StrollHistoryCategoryUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
  update: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateWithoutCategoryInput, Prisma.StrollHistoryCategoryUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.StrollHistoryCategoryCreateWithoutCategoryInput, Prisma.StrollHistoryCategoryUncheckedCreateWithoutCategoryInput>
}

export type StrollHistoryCategoryUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
  data: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateWithoutCategoryInput, Prisma.StrollHistoryCategoryUncheckedUpdateWithoutCategoryInput>
}

export type StrollHistoryCategoryUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.StrollHistoryCategoryScalarWhereInput
  data: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateManyMutationInput, Prisma.StrollHistoryCategoryUncheckedUpdateManyWithoutCategoryInput>
}

export type StrollHistoryCategoryCreateManyStrollHistoryInput = {
  categoryId: string
}

export type StrollHistoryCategoryUpdateWithoutStrollHistoryInput = {
  category?: Prisma.CategoryUpdateOneRequiredWithoutStrollHistoriesNestedInput
}

export type StrollHistoryCategoryUncheckedUpdateWithoutStrollHistoryInput = {
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StrollHistoryCategoryUncheckedUpdateManyWithoutStrollHistoryInput = {
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StrollHistoryCategoryCreateManyCategoryInput = {
  strollHistoryId: string
}

export type StrollHistoryCategoryUpdateWithoutCategoryInput = {
  strollHistory?: Prisma.StrollHistoryUpdateOneRequiredWithoutCategoriesNestedInput
}

export type StrollHistoryCategoryUncheckedUpdateWithoutCategoryInput = {
  strollHistoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StrollHistoryCategoryUncheckedUpdateManyWithoutCategoryInput = {
  strollHistoryId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type StrollHistoryCategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  strollHistoryId?: boolean
  categoryId?: boolean
  strollHistory?: boolean | Prisma.StrollHistoryDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["strollHistoryCategory"]>

export type StrollHistoryCategorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  strollHistoryId?: boolean
  categoryId?: boolean
  strollHistory?: boolean | Prisma.StrollHistoryDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["strollHistoryCategory"]>

export type StrollHistoryCategorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  strollHistoryId?: boolean
  categoryId?: boolean
  strollHistory?: boolean | Prisma.StrollHistoryDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["strollHistoryCategory"]>

export type StrollHistoryCategorySelectScalar = {
  strollHistoryId?: boolean
  categoryId?: boolean
}

export type StrollHistoryCategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"strollHistoryId" | "categoryId", ExtArgs["result"]["strollHistoryCategory"]>
export type StrollHistoryCategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  strollHistory?: boolean | Prisma.StrollHistoryDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type StrollHistoryCategoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  strollHistory?: boolean | Prisma.StrollHistoryDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type StrollHistoryCategoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  strollHistory?: boolean | Prisma.StrollHistoryDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}

export type $StrollHistoryCategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StrollHistoryCategory"
  objects: {
    strollHistory: Prisma.$StrollHistoryPayload<ExtArgs>
    category: Prisma.$CategoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    strollHistoryId: string
    categoryId: string
  }, ExtArgs["result"]["strollHistoryCategory"]>
  composites: {}
}

export type StrollHistoryCategoryGetPayload<S extends boolean | null | undefined | StrollHistoryCategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload, S>

export type StrollHistoryCategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StrollHistoryCategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StrollHistoryCategoryCountAggregateInputType | true
  }

export interface StrollHistoryCategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StrollHistoryCategory'], meta: { name: 'StrollHistoryCategory' } }
  /**
   * Find zero or one StrollHistoryCategory that matches the filter.
   * @param {StrollHistoryCategoryFindUniqueArgs} args - Arguments to find a StrollHistoryCategory
   * @example
   * // Get one StrollHistoryCategory
   * const strollHistoryCategory = await prisma.strollHistoryCategory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StrollHistoryCategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, StrollHistoryCategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryCategoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StrollHistoryCategory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StrollHistoryCategoryFindUniqueOrThrowArgs} args - Arguments to find a StrollHistoryCategory
   * @example
   * // Get one StrollHistoryCategory
   * const strollHistoryCategory = await prisma.strollHistoryCategory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StrollHistoryCategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StrollHistoryCategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryCategoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StrollHistoryCategory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryCategoryFindFirstArgs} args - Arguments to find a StrollHistoryCategory
   * @example
   * // Get one StrollHistoryCategory
   * const strollHistoryCategory = await prisma.strollHistoryCategory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StrollHistoryCategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, StrollHistoryCategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryCategoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StrollHistoryCategory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryCategoryFindFirstOrThrowArgs} args - Arguments to find a StrollHistoryCategory
   * @example
   * // Get one StrollHistoryCategory
   * const strollHistoryCategory = await prisma.strollHistoryCategory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StrollHistoryCategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StrollHistoryCategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryCategoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StrollHistoryCategories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryCategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StrollHistoryCategories
   * const strollHistoryCategories = await prisma.strollHistoryCategory.findMany()
   * 
   * // Get first 10 StrollHistoryCategories
   * const strollHistoryCategories = await prisma.strollHistoryCategory.findMany({ take: 10 })
   * 
   * // Only select the `strollHistoryId`
   * const strollHistoryCategoryWithStrollHistoryIdOnly = await prisma.strollHistoryCategory.findMany({ select: { strollHistoryId: true } })
   * 
   */
  findMany<T extends StrollHistoryCategoryFindManyArgs>(args?: Prisma.SelectSubset<T, StrollHistoryCategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StrollHistoryCategory.
   * @param {StrollHistoryCategoryCreateArgs} args - Arguments to create a StrollHistoryCategory.
   * @example
   * // Create one StrollHistoryCategory
   * const StrollHistoryCategory = await prisma.strollHistoryCategory.create({
   *   data: {
   *     // ... data to create a StrollHistoryCategory
   *   }
   * })
   * 
   */
  create<T extends StrollHistoryCategoryCreateArgs>(args: Prisma.SelectSubset<T, StrollHistoryCategoryCreateArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryCategoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StrollHistoryCategories.
   * @param {StrollHistoryCategoryCreateManyArgs} args - Arguments to create many StrollHistoryCategories.
   * @example
   * // Create many StrollHistoryCategories
   * const strollHistoryCategory = await prisma.strollHistoryCategory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StrollHistoryCategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, StrollHistoryCategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StrollHistoryCategories and returns the data saved in the database.
   * @param {StrollHistoryCategoryCreateManyAndReturnArgs} args - Arguments to create many StrollHistoryCategories.
   * @example
   * // Create many StrollHistoryCategories
   * const strollHistoryCategory = await prisma.strollHistoryCategory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StrollHistoryCategories and only return the `strollHistoryId`
   * const strollHistoryCategoryWithStrollHistoryIdOnly = await prisma.strollHistoryCategory.createManyAndReturn({
   *   select: { strollHistoryId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StrollHistoryCategoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StrollHistoryCategoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StrollHistoryCategory.
   * @param {StrollHistoryCategoryDeleteArgs} args - Arguments to delete one StrollHistoryCategory.
   * @example
   * // Delete one StrollHistoryCategory
   * const StrollHistoryCategory = await prisma.strollHistoryCategory.delete({
   *   where: {
   *     // ... filter to delete one StrollHistoryCategory
   *   }
   * })
   * 
   */
  delete<T extends StrollHistoryCategoryDeleteArgs>(args: Prisma.SelectSubset<T, StrollHistoryCategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryCategoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StrollHistoryCategory.
   * @param {StrollHistoryCategoryUpdateArgs} args - Arguments to update one StrollHistoryCategory.
   * @example
   * // Update one StrollHistoryCategory
   * const strollHistoryCategory = await prisma.strollHistoryCategory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StrollHistoryCategoryUpdateArgs>(args: Prisma.SelectSubset<T, StrollHistoryCategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryCategoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StrollHistoryCategories.
   * @param {StrollHistoryCategoryDeleteManyArgs} args - Arguments to filter StrollHistoryCategories to delete.
   * @example
   * // Delete a few StrollHistoryCategories
   * const { count } = await prisma.strollHistoryCategory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StrollHistoryCategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, StrollHistoryCategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StrollHistoryCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryCategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StrollHistoryCategories
   * const strollHistoryCategory = await prisma.strollHistoryCategory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StrollHistoryCategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, StrollHistoryCategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StrollHistoryCategories and returns the data updated in the database.
   * @param {StrollHistoryCategoryUpdateManyAndReturnArgs} args - Arguments to update many StrollHistoryCategories.
   * @example
   * // Update many StrollHistoryCategories
   * const strollHistoryCategory = await prisma.strollHistoryCategory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StrollHistoryCategories and only return the `strollHistoryId`
   * const strollHistoryCategoryWithStrollHistoryIdOnly = await prisma.strollHistoryCategory.updateManyAndReturn({
   *   select: { strollHistoryId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StrollHistoryCategoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StrollHistoryCategoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StrollHistoryCategory.
   * @param {StrollHistoryCategoryUpsertArgs} args - Arguments to update or create a StrollHistoryCategory.
   * @example
   * // Update or create a StrollHistoryCategory
   * const strollHistoryCategory = await prisma.strollHistoryCategory.upsert({
   *   create: {
   *     // ... data to create a StrollHistoryCategory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StrollHistoryCategory we want to update
   *   }
   * })
   */
  upsert<T extends StrollHistoryCategoryUpsertArgs>(args: Prisma.SelectSubset<T, StrollHistoryCategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryCategoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StrollHistoryCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryCategoryCountArgs} args - Arguments to filter StrollHistoryCategories to count.
   * @example
   * // Count the number of StrollHistoryCategories
   * const count = await prisma.strollHistoryCategory.count({
   *   where: {
   *     // ... the filter for the StrollHistoryCategories we want to count
   *   }
   * })
  **/
  count<T extends StrollHistoryCategoryCountArgs>(
    args?: Prisma.Subset<T, StrollHistoryCategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StrollHistoryCategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StrollHistoryCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryCategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StrollHistoryCategoryAggregateArgs>(args: Prisma.Subset<T, StrollHistoryCategoryAggregateArgs>): Prisma.PrismaPromise<GetStrollHistoryCategoryAggregateType<T>>

  /**
   * Group by StrollHistoryCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryCategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StrollHistoryCategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StrollHistoryCategoryGroupByArgs['orderBy'] }
      : { orderBy?: StrollHistoryCategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StrollHistoryCategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStrollHistoryCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StrollHistoryCategory model
 */
readonly fields: StrollHistoryCategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StrollHistoryCategory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StrollHistoryCategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  strollHistory<T extends Prisma.StrollHistoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StrollHistoryDefaultArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  category<T extends Prisma.CategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StrollHistoryCategory model
 */
export interface StrollHistoryCategoryFieldRefs {
  readonly strollHistoryId: Prisma.FieldRef<"StrollHistoryCategory", 'String'>
  readonly categoryId: Prisma.FieldRef<"StrollHistoryCategory", 'String'>
}
    

// Custom InputTypes
/**
 * StrollHistoryCategory findUnique
 */
export type StrollHistoryCategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistoryCategory to fetch.
   */
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
}

/**
 * StrollHistoryCategory findUniqueOrThrow
 */
export type StrollHistoryCategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistoryCategory to fetch.
   */
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
}

/**
 * StrollHistoryCategory findFirst
 */
export type StrollHistoryCategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistoryCategory to fetch.
   */
  where?: Prisma.StrollHistoryCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StrollHistoryCategories to fetch.
   */
  orderBy?: Prisma.StrollHistoryCategoryOrderByWithRelationInput | Prisma.StrollHistoryCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StrollHistoryCategories.
   */
  cursor?: Prisma.StrollHistoryCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StrollHistoryCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StrollHistoryCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StrollHistoryCategories.
   */
  distinct?: Prisma.StrollHistoryCategoryScalarFieldEnum | Prisma.StrollHistoryCategoryScalarFieldEnum[]
}

/**
 * StrollHistoryCategory findFirstOrThrow
 */
export type StrollHistoryCategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistoryCategory to fetch.
   */
  where?: Prisma.StrollHistoryCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StrollHistoryCategories to fetch.
   */
  orderBy?: Prisma.StrollHistoryCategoryOrderByWithRelationInput | Prisma.StrollHistoryCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StrollHistoryCategories.
   */
  cursor?: Prisma.StrollHistoryCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StrollHistoryCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StrollHistoryCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StrollHistoryCategories.
   */
  distinct?: Prisma.StrollHistoryCategoryScalarFieldEnum | Prisma.StrollHistoryCategoryScalarFieldEnum[]
}

/**
 * StrollHistoryCategory findMany
 */
export type StrollHistoryCategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistoryCategories to fetch.
   */
  where?: Prisma.StrollHistoryCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StrollHistoryCategories to fetch.
   */
  orderBy?: Prisma.StrollHistoryCategoryOrderByWithRelationInput | Prisma.StrollHistoryCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StrollHistoryCategories.
   */
  cursor?: Prisma.StrollHistoryCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StrollHistoryCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StrollHistoryCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StrollHistoryCategories.
   */
  distinct?: Prisma.StrollHistoryCategoryScalarFieldEnum | Prisma.StrollHistoryCategoryScalarFieldEnum[]
}

/**
 * StrollHistoryCategory create
 */
export type StrollHistoryCategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a StrollHistoryCategory.
   */
  data: Prisma.XOR<Prisma.StrollHistoryCategoryCreateInput, Prisma.StrollHistoryCategoryUncheckedCreateInput>
}

/**
 * StrollHistoryCategory createMany
 */
export type StrollHistoryCategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StrollHistoryCategories.
   */
  data: Prisma.StrollHistoryCategoryCreateManyInput | Prisma.StrollHistoryCategoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StrollHistoryCategory createManyAndReturn
 */
export type StrollHistoryCategoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * The data used to create many StrollHistoryCategories.
   */
  data: Prisma.StrollHistoryCategoryCreateManyInput | Prisma.StrollHistoryCategoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StrollHistoryCategory update
 */
export type StrollHistoryCategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a StrollHistoryCategory.
   */
  data: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateInput, Prisma.StrollHistoryCategoryUncheckedUpdateInput>
  /**
   * Choose, which StrollHistoryCategory to update.
   */
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
}

/**
 * StrollHistoryCategory updateMany
 */
export type StrollHistoryCategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StrollHistoryCategories.
   */
  data: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateManyMutationInput, Prisma.StrollHistoryCategoryUncheckedUpdateManyInput>
  /**
   * Filter which StrollHistoryCategories to update
   */
  where?: Prisma.StrollHistoryCategoryWhereInput
  /**
   * Limit how many StrollHistoryCategories to update.
   */
  limit?: number
}

/**
 * StrollHistoryCategory updateManyAndReturn
 */
export type StrollHistoryCategoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * The data used to update StrollHistoryCategories.
   */
  data: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateManyMutationInput, Prisma.StrollHistoryCategoryUncheckedUpdateManyInput>
  /**
   * Filter which StrollHistoryCategories to update
   */
  where?: Prisma.StrollHistoryCategoryWhereInput
  /**
   * Limit how many StrollHistoryCategories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StrollHistoryCategory upsert
 */
export type StrollHistoryCategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the StrollHistoryCategory to update in case it exists.
   */
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
  /**
   * In case the StrollHistoryCategory found by the `where` argument doesn't exist, create a new StrollHistoryCategory with this data.
   */
  create: Prisma.XOR<Prisma.StrollHistoryCategoryCreateInput, Prisma.StrollHistoryCategoryUncheckedCreateInput>
  /**
   * In case the StrollHistoryCategory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StrollHistoryCategoryUpdateInput, Prisma.StrollHistoryCategoryUncheckedUpdateInput>
}

/**
 * StrollHistoryCategory delete
 */
export type StrollHistoryCategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  /**
   * Filter which StrollHistoryCategory to delete.
   */
  where: Prisma.StrollHistoryCategoryWhereUniqueInput
}

/**
 * StrollHistoryCategory deleteMany
 */
export type StrollHistoryCategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StrollHistoryCategories to delete
   */
  where?: Prisma.StrollHistoryCategoryWhereInput
  /**
   * Limit how many StrollHistoryCategories to delete.
   */
  limit?: number
}

/**
 * StrollHistoryCategory without action
 */
export type StrollHistoryCategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
}
