
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StrollHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StrollHistory
 * 
 */
export type StrollHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$StrollHistoryPayload>

export type AggregateStrollHistory = {
  _count: StrollHistoryCountAggregateOutputType | null
  _avg: StrollHistoryAvgAggregateOutputType | null
  _sum: StrollHistorySumAggregateOutputType | null
  _min: StrollHistoryMinAggregateOutputType | null
  _max: StrollHistoryMaxAggregateOutputType | null
}

export type StrollHistoryAvgAggregateOutputType = {
  strollTime: number | null
  meter: number | null
  steps: number | null
  calories: runtime.Decimal | null
}

export type StrollHistorySumAggregateOutputType = {
  strollTime: number | null
  meter: number | null
  steps: number | null
  calories: runtime.Decimal | null
}

export type StrollHistoryMinAggregateOutputType = {
  id: string | null
  userId: string | null
  visitedPlaceId: string | null
  placeName: string | null
  visitedAt: Date | null
  strollTime: number | null
  meter: number | null
  steps: number | null
  calories: runtime.Decimal | null
}

export type StrollHistoryMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  visitedPlaceId: string | null
  placeName: string | null
  visitedAt: Date | null
  strollTime: number | null
  meter: number | null
  steps: number | null
  calories: runtime.Decimal | null
}

export type StrollHistoryCountAggregateOutputType = {
  id: number
  userId: number
  visitedPlaceId: number
  placeName: number
  visitedAt: number
  strollTime: number
  meter: number
  steps: number
  calories: number
  _all: number
}


export type StrollHistoryAvgAggregateInputType = {
  strollTime?: true
  meter?: true
  steps?: true
  calories?: true
}

export type StrollHistorySumAggregateInputType = {
  strollTime?: true
  meter?: true
  steps?: true
  calories?: true
}

export type StrollHistoryMinAggregateInputType = {
  id?: true
  userId?: true
  visitedPlaceId?: true
  placeName?: true
  visitedAt?: true
  strollTime?: true
  meter?: true
  steps?: true
  calories?: true
}

export type StrollHistoryMaxAggregateInputType = {
  id?: true
  userId?: true
  visitedPlaceId?: true
  placeName?: true
  visitedAt?: true
  strollTime?: true
  meter?: true
  steps?: true
  calories?: true
}

export type StrollHistoryCountAggregateInputType = {
  id?: true
  userId?: true
  visitedPlaceId?: true
  placeName?: true
  visitedAt?: true
  strollTime?: true
  meter?: true
  steps?: true
  calories?: true
  _all?: true
}

export type StrollHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StrollHistory to aggregate.
   */
  where?: Prisma.StrollHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StrollHistories to fetch.
   */
  orderBy?: Prisma.StrollHistoryOrderByWithRelationInput | Prisma.StrollHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StrollHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StrollHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StrollHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StrollHistories
  **/
  _count?: true | StrollHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StrollHistoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StrollHistorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StrollHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StrollHistoryMaxAggregateInputType
}

export type GetStrollHistoryAggregateType<T extends StrollHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateStrollHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStrollHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateStrollHistory[P]>
}




export type StrollHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StrollHistoryWhereInput
  orderBy?: Prisma.StrollHistoryOrderByWithAggregationInput | Prisma.StrollHistoryOrderByWithAggregationInput[]
  by: Prisma.StrollHistoryScalarFieldEnum[] | Prisma.StrollHistoryScalarFieldEnum
  having?: Prisma.StrollHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StrollHistoryCountAggregateInputType | true
  _avg?: StrollHistoryAvgAggregateInputType
  _sum?: StrollHistorySumAggregateInputType
  _min?: StrollHistoryMinAggregateInputType
  _max?: StrollHistoryMaxAggregateInputType
}

export type StrollHistoryGroupByOutputType = {
  id: string
  userId: string
  visitedPlaceId: string
  placeName: string | null
  visitedAt: Date
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal
  _count: StrollHistoryCountAggregateOutputType | null
  _avg: StrollHistoryAvgAggregateOutputType | null
  _sum: StrollHistorySumAggregateOutputType | null
  _min: StrollHistoryMinAggregateOutputType | null
  _max: StrollHistoryMaxAggregateOutputType | null
}

export type GetStrollHistoryGroupByPayload<T extends StrollHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StrollHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StrollHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StrollHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StrollHistoryGroupByOutputType[P]>
      }
    >
  >



export type StrollHistoryWhereInput = {
  AND?: Prisma.StrollHistoryWhereInput | Prisma.StrollHistoryWhereInput[]
  OR?: Prisma.StrollHistoryWhereInput[]
  NOT?: Prisma.StrollHistoryWhereInput | Prisma.StrollHistoryWhereInput[]
  id?: Prisma.StringFilter<"StrollHistory"> | string
  userId?: Prisma.StringFilter<"StrollHistory"> | string
  visitedPlaceId?: Prisma.StringFilter<"StrollHistory"> | string
  placeName?: Prisma.StringNullableFilter<"StrollHistory"> | string | null
  visitedAt?: Prisma.DateTimeFilter<"StrollHistory"> | Date | string
  strollTime?: Prisma.IntFilter<"StrollHistory"> | number
  meter?: Prisma.IntFilter<"StrollHistory"> | number
  steps?: Prisma.IntFilter<"StrollHistory"> | number
  calories?: Prisma.DecimalFilter<"StrollHistory"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  pictures?: Prisma.PictureListRelationFilter
  categories?: Prisma.StrollHistoryCategoryListRelationFilter
}

export type StrollHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  visitedPlaceId?: Prisma.SortOrder
  placeName?: Prisma.SortOrderInput | Prisma.SortOrder
  visitedAt?: Prisma.SortOrder
  strollTime?: Prisma.SortOrder
  meter?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  calories?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  pictures?: Prisma.PictureOrderByRelationAggregateInput
  categories?: Prisma.StrollHistoryCategoryOrderByRelationAggregateInput
}

export type StrollHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StrollHistoryWhereInput | Prisma.StrollHistoryWhereInput[]
  OR?: Prisma.StrollHistoryWhereInput[]
  NOT?: Prisma.StrollHistoryWhereInput | Prisma.StrollHistoryWhereInput[]
  userId?: Prisma.StringFilter<"StrollHistory"> | string
  visitedPlaceId?: Prisma.StringFilter<"StrollHistory"> | string
  placeName?: Prisma.StringNullableFilter<"StrollHistory"> | string | null
  visitedAt?: Prisma.DateTimeFilter<"StrollHistory"> | Date | string
  strollTime?: Prisma.IntFilter<"StrollHistory"> | number
  meter?: Prisma.IntFilter<"StrollHistory"> | number
  steps?: Prisma.IntFilter<"StrollHistory"> | number
  calories?: Prisma.DecimalFilter<"StrollHistory"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  pictures?: Prisma.PictureListRelationFilter
  categories?: Prisma.StrollHistoryCategoryListRelationFilter
}, "id">

export type StrollHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  visitedPlaceId?: Prisma.SortOrder
  placeName?: Prisma.SortOrderInput | Prisma.SortOrder
  visitedAt?: Prisma.SortOrder
  strollTime?: Prisma.SortOrder
  meter?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  calories?: Prisma.SortOrder
  _count?: Prisma.StrollHistoryCountOrderByAggregateInput
  _avg?: Prisma.StrollHistoryAvgOrderByAggregateInput
  _max?: Prisma.StrollHistoryMaxOrderByAggregateInput
  _min?: Prisma.StrollHistoryMinOrderByAggregateInput
  _sum?: Prisma.StrollHistorySumOrderByAggregateInput
}

export type StrollHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.StrollHistoryScalarWhereWithAggregatesInput | Prisma.StrollHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.StrollHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StrollHistoryScalarWhereWithAggregatesInput | Prisma.StrollHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StrollHistory"> | string
  userId?: Prisma.StringWithAggregatesFilter<"StrollHistory"> | string
  visitedPlaceId?: Prisma.StringWithAggregatesFilter<"StrollHistory"> | string
  placeName?: Prisma.StringNullableWithAggregatesFilter<"StrollHistory"> | string | null
  visitedAt?: Prisma.DateTimeWithAggregatesFilter<"StrollHistory"> | Date | string
  strollTime?: Prisma.IntWithAggregatesFilter<"StrollHistory"> | number
  meter?: Prisma.IntWithAggregatesFilter<"StrollHistory"> | number
  steps?: Prisma.IntWithAggregatesFilter<"StrollHistory"> | number
  calories?: Prisma.DecimalWithAggregatesFilter<"StrollHistory"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type StrollHistoryCreateInput = {
  id?: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
  user: Prisma.UserCreateNestedOneWithoutStrollHistoriesInput
  pictures?: Prisma.PictureCreateNestedManyWithoutStrollHistoryInput
  categories?: Prisma.StrollHistoryCategoryCreateNestedManyWithoutStrollHistoryInput
}

export type StrollHistoryUncheckedCreateInput = {
  id?: string
  userId: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
  pictures?: Prisma.PictureUncheckedCreateNestedManyWithoutStrollHistoryInput
  categories?: Prisma.StrollHistoryCategoryUncheckedCreateNestedManyWithoutStrollHistoryInput
}

export type StrollHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  user?: Prisma.UserUpdateOneRequiredWithoutStrollHistoriesNestedInput
  pictures?: Prisma.PictureUpdateManyWithoutStrollHistoryNestedInput
  categories?: Prisma.StrollHistoryCategoryUpdateManyWithoutStrollHistoryNestedInput
}

export type StrollHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pictures?: Prisma.PictureUncheckedUpdateManyWithoutStrollHistoryNestedInput
  categories?: Prisma.StrollHistoryCategoryUncheckedUpdateManyWithoutStrollHistoryNestedInput
}

export type StrollHistoryCreateManyInput = {
  id?: string
  userId: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type StrollHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type StrollHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type StrollHistoryListRelationFilter = {
  every?: Prisma.StrollHistoryWhereInput
  some?: Prisma.StrollHistoryWhereInput
  none?: Prisma.StrollHistoryWhereInput
}

export type StrollHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StrollHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  visitedPlaceId?: Prisma.SortOrder
  placeName?: Prisma.SortOrder
  visitedAt?: Prisma.SortOrder
  strollTime?: Prisma.SortOrder
  meter?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  calories?: Prisma.SortOrder
}

export type StrollHistoryAvgOrderByAggregateInput = {
  strollTime?: Prisma.SortOrder
  meter?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  calories?: Prisma.SortOrder
}

export type StrollHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  visitedPlaceId?: Prisma.SortOrder
  placeName?: Prisma.SortOrder
  visitedAt?: Prisma.SortOrder
  strollTime?: Prisma.SortOrder
  meter?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  calories?: Prisma.SortOrder
}

export type StrollHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  visitedPlaceId?: Prisma.SortOrder
  placeName?: Prisma.SortOrder
  visitedAt?: Prisma.SortOrder
  strollTime?: Prisma.SortOrder
  meter?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  calories?: Prisma.SortOrder
}

export type StrollHistorySumOrderByAggregateInput = {
  strollTime?: Prisma.SortOrder
  meter?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  calories?: Prisma.SortOrder
}

export type StrollHistoryScalarRelationFilter = {
  is?: Prisma.StrollHistoryWhereInput
  isNot?: Prisma.StrollHistoryWhereInput
}

export type StrollHistoryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCreateWithoutUserInput, Prisma.StrollHistoryUncheckedCreateWithoutUserInput> | Prisma.StrollHistoryCreateWithoutUserInput[] | Prisma.StrollHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StrollHistoryCreateOrConnectWithoutUserInput | Prisma.StrollHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StrollHistoryCreateManyUserInputEnvelope
  connect?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
}

export type StrollHistoryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCreateWithoutUserInput, Prisma.StrollHistoryUncheckedCreateWithoutUserInput> | Prisma.StrollHistoryCreateWithoutUserInput[] | Prisma.StrollHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StrollHistoryCreateOrConnectWithoutUserInput | Prisma.StrollHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StrollHistoryCreateManyUserInputEnvelope
  connect?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
}

export type StrollHistoryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCreateWithoutUserInput, Prisma.StrollHistoryUncheckedCreateWithoutUserInput> | Prisma.StrollHistoryCreateWithoutUserInput[] | Prisma.StrollHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StrollHistoryCreateOrConnectWithoutUserInput | Prisma.StrollHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StrollHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.StrollHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StrollHistoryCreateManyUserInputEnvelope
  set?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
  disconnect?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
  delete?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
  connect?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
  update?: Prisma.StrollHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.StrollHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StrollHistoryUpdateManyWithWhereWithoutUserInput | Prisma.StrollHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StrollHistoryScalarWhereInput | Prisma.StrollHistoryScalarWhereInput[]
}

export type StrollHistoryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCreateWithoutUserInput, Prisma.StrollHistoryUncheckedCreateWithoutUserInput> | Prisma.StrollHistoryCreateWithoutUserInput[] | Prisma.StrollHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StrollHistoryCreateOrConnectWithoutUserInput | Prisma.StrollHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StrollHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.StrollHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StrollHistoryCreateManyUserInputEnvelope
  set?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
  disconnect?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
  delete?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
  connect?: Prisma.StrollHistoryWhereUniqueInput | Prisma.StrollHistoryWhereUniqueInput[]
  update?: Prisma.StrollHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.StrollHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StrollHistoryUpdateManyWithWhereWithoutUserInput | Prisma.StrollHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StrollHistoryScalarWhereInput | Prisma.StrollHistoryScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type StrollHistoryCreateNestedOneWithoutCategoriesInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCreateWithoutCategoriesInput, Prisma.StrollHistoryUncheckedCreateWithoutCategoriesInput>
  connectOrCreate?: Prisma.StrollHistoryCreateOrConnectWithoutCategoriesInput
  connect?: Prisma.StrollHistoryWhereUniqueInput
}

export type StrollHistoryUpdateOneRequiredWithoutCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCreateWithoutCategoriesInput, Prisma.StrollHistoryUncheckedCreateWithoutCategoriesInput>
  connectOrCreate?: Prisma.StrollHistoryCreateOrConnectWithoutCategoriesInput
  upsert?: Prisma.StrollHistoryUpsertWithoutCategoriesInput
  connect?: Prisma.StrollHistoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StrollHistoryUpdateToOneWithWhereWithoutCategoriesInput, Prisma.StrollHistoryUpdateWithoutCategoriesInput>, Prisma.StrollHistoryUncheckedUpdateWithoutCategoriesInput>
}

export type StrollHistoryCreateNestedOneWithoutPicturesInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCreateWithoutPicturesInput, Prisma.StrollHistoryUncheckedCreateWithoutPicturesInput>
  connectOrCreate?: Prisma.StrollHistoryCreateOrConnectWithoutPicturesInput
  connect?: Prisma.StrollHistoryWhereUniqueInput
}

export type StrollHistoryUpdateOneRequiredWithoutPicturesNestedInput = {
  create?: Prisma.XOR<Prisma.StrollHistoryCreateWithoutPicturesInput, Prisma.StrollHistoryUncheckedCreateWithoutPicturesInput>
  connectOrCreate?: Prisma.StrollHistoryCreateOrConnectWithoutPicturesInput
  upsert?: Prisma.StrollHistoryUpsertWithoutPicturesInput
  connect?: Prisma.StrollHistoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StrollHistoryUpdateToOneWithWhereWithoutPicturesInput, Prisma.StrollHistoryUpdateWithoutPicturesInput>, Prisma.StrollHistoryUncheckedUpdateWithoutPicturesInput>
}

export type StrollHistoryCreateWithoutUserInput = {
  id?: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
  pictures?: Prisma.PictureCreateNestedManyWithoutStrollHistoryInput
  categories?: Prisma.StrollHistoryCategoryCreateNestedManyWithoutStrollHistoryInput
}

export type StrollHistoryUncheckedCreateWithoutUserInput = {
  id?: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
  pictures?: Prisma.PictureUncheckedCreateNestedManyWithoutStrollHistoryInput
  categories?: Prisma.StrollHistoryCategoryUncheckedCreateNestedManyWithoutStrollHistoryInput
}

export type StrollHistoryCreateOrConnectWithoutUserInput = {
  where: Prisma.StrollHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.StrollHistoryCreateWithoutUserInput, Prisma.StrollHistoryUncheckedCreateWithoutUserInput>
}

export type StrollHistoryCreateManyUserInputEnvelope = {
  data: Prisma.StrollHistoryCreateManyUserInput | Prisma.StrollHistoryCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type StrollHistoryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.StrollHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.StrollHistoryUpdateWithoutUserInput, Prisma.StrollHistoryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StrollHistoryCreateWithoutUserInput, Prisma.StrollHistoryUncheckedCreateWithoutUserInput>
}

export type StrollHistoryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.StrollHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.StrollHistoryUpdateWithoutUserInput, Prisma.StrollHistoryUncheckedUpdateWithoutUserInput>
}

export type StrollHistoryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.StrollHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.StrollHistoryUpdateManyMutationInput, Prisma.StrollHistoryUncheckedUpdateManyWithoutUserInput>
}

export type StrollHistoryScalarWhereInput = {
  AND?: Prisma.StrollHistoryScalarWhereInput | Prisma.StrollHistoryScalarWhereInput[]
  OR?: Prisma.StrollHistoryScalarWhereInput[]
  NOT?: Prisma.StrollHistoryScalarWhereInput | Prisma.StrollHistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"StrollHistory"> | string
  userId?: Prisma.StringFilter<"StrollHistory"> | string
  visitedPlaceId?: Prisma.StringFilter<"StrollHistory"> | string
  placeName?: Prisma.StringNullableFilter<"StrollHistory"> | string | null
  visitedAt?: Prisma.DateTimeFilter<"StrollHistory"> | Date | string
  strollTime?: Prisma.IntFilter<"StrollHistory"> | number
  meter?: Prisma.IntFilter<"StrollHistory"> | number
  steps?: Prisma.IntFilter<"StrollHistory"> | number
  calories?: Prisma.DecimalFilter<"StrollHistory"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type StrollHistoryCreateWithoutCategoriesInput = {
  id?: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
  user: Prisma.UserCreateNestedOneWithoutStrollHistoriesInput
  pictures?: Prisma.PictureCreateNestedManyWithoutStrollHistoryInput
}

export type StrollHistoryUncheckedCreateWithoutCategoriesInput = {
  id?: string
  userId: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
  pictures?: Prisma.PictureUncheckedCreateNestedManyWithoutStrollHistoryInput
}

export type StrollHistoryCreateOrConnectWithoutCategoriesInput = {
  where: Prisma.StrollHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.StrollHistoryCreateWithoutCategoriesInput, Prisma.StrollHistoryUncheckedCreateWithoutCategoriesInput>
}

export type StrollHistoryUpsertWithoutCategoriesInput = {
  update: Prisma.XOR<Prisma.StrollHistoryUpdateWithoutCategoriesInput, Prisma.StrollHistoryUncheckedUpdateWithoutCategoriesInput>
  create: Prisma.XOR<Prisma.StrollHistoryCreateWithoutCategoriesInput, Prisma.StrollHistoryUncheckedCreateWithoutCategoriesInput>
  where?: Prisma.StrollHistoryWhereInput
}

export type StrollHistoryUpdateToOneWithWhereWithoutCategoriesInput = {
  where?: Prisma.StrollHistoryWhereInput
  data: Prisma.XOR<Prisma.StrollHistoryUpdateWithoutCategoriesInput, Prisma.StrollHistoryUncheckedUpdateWithoutCategoriesInput>
}

export type StrollHistoryUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  user?: Prisma.UserUpdateOneRequiredWithoutStrollHistoriesNestedInput
  pictures?: Prisma.PictureUpdateManyWithoutStrollHistoryNestedInput
}

export type StrollHistoryUncheckedUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pictures?: Prisma.PictureUncheckedUpdateManyWithoutStrollHistoryNestedInput
}

export type StrollHistoryCreateWithoutPicturesInput = {
  id?: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
  user: Prisma.UserCreateNestedOneWithoutStrollHistoriesInput
  categories?: Prisma.StrollHistoryCategoryCreateNestedManyWithoutStrollHistoryInput
}

export type StrollHistoryUncheckedCreateWithoutPicturesInput = {
  id?: string
  userId: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
  categories?: Prisma.StrollHistoryCategoryUncheckedCreateNestedManyWithoutStrollHistoryInput
}

export type StrollHistoryCreateOrConnectWithoutPicturesInput = {
  where: Prisma.StrollHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.StrollHistoryCreateWithoutPicturesInput, Prisma.StrollHistoryUncheckedCreateWithoutPicturesInput>
}

export type StrollHistoryUpsertWithoutPicturesInput = {
  update: Prisma.XOR<Prisma.StrollHistoryUpdateWithoutPicturesInput, Prisma.StrollHistoryUncheckedUpdateWithoutPicturesInput>
  create: Prisma.XOR<Prisma.StrollHistoryCreateWithoutPicturesInput, Prisma.StrollHistoryUncheckedCreateWithoutPicturesInput>
  where?: Prisma.StrollHistoryWhereInput
}

export type StrollHistoryUpdateToOneWithWhereWithoutPicturesInput = {
  where?: Prisma.StrollHistoryWhereInput
  data: Prisma.XOR<Prisma.StrollHistoryUpdateWithoutPicturesInput, Prisma.StrollHistoryUncheckedUpdateWithoutPicturesInput>
}

export type StrollHistoryUpdateWithoutPicturesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  user?: Prisma.UserUpdateOneRequiredWithoutStrollHistoriesNestedInput
  categories?: Prisma.StrollHistoryCategoryUpdateManyWithoutStrollHistoryNestedInput
}

export type StrollHistoryUncheckedUpdateWithoutPicturesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  categories?: Prisma.StrollHistoryCategoryUncheckedUpdateManyWithoutStrollHistoryNestedInput
}

export type StrollHistoryCreateManyUserInput = {
  id?: string
  visitedPlaceId: string
  placeName?: string | null
  visitedAt: Date | string
  strollTime: number
  meter: number
  steps: number
  calories: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type StrollHistoryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pictures?: Prisma.PictureUpdateManyWithoutStrollHistoryNestedInput
  categories?: Prisma.StrollHistoryCategoryUpdateManyWithoutStrollHistoryNestedInput
}

export type StrollHistoryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pictures?: Prisma.PictureUncheckedUpdateManyWithoutStrollHistoryNestedInput
  categories?: Prisma.StrollHistoryCategoryUncheckedUpdateManyWithoutStrollHistoryNestedInput
}

export type StrollHistoryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visitedPlaceId?: Prisma.StringFieldUpdateOperationsInput | string
  placeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  strollTime?: Prisma.IntFieldUpdateOperationsInput | number
  meter?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.IntFieldUpdateOperationsInput | number
  calories?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}


/**
 * Count Type StrollHistoryCountOutputType
 */

export type StrollHistoryCountOutputType = {
  pictures: number
  categories: number
}

export type StrollHistoryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pictures?: boolean | StrollHistoryCountOutputTypeCountPicturesArgs
  categories?: boolean | StrollHistoryCountOutputTypeCountCategoriesArgs
}

/**
 * StrollHistoryCountOutputType without action
 */
export type StrollHistoryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCountOutputType
   */
  select?: Prisma.StrollHistoryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StrollHistoryCountOutputType without action
 */
export type StrollHistoryCountOutputTypeCountPicturesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PictureWhereInput
}

/**
 * StrollHistoryCountOutputType without action
 */
export type StrollHistoryCountOutputTypeCountCategoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StrollHistoryCategoryWhereInput
}


export type StrollHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  visitedPlaceId?: boolean
  placeName?: boolean
  visitedAt?: boolean
  strollTime?: boolean
  meter?: boolean
  steps?: boolean
  calories?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  pictures?: boolean | Prisma.StrollHistory$picturesArgs<ExtArgs>
  categories?: boolean | Prisma.StrollHistory$categoriesArgs<ExtArgs>
  _count?: boolean | Prisma.StrollHistoryCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["strollHistory"]>

export type StrollHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  visitedPlaceId?: boolean
  placeName?: boolean
  visitedAt?: boolean
  strollTime?: boolean
  meter?: boolean
  steps?: boolean
  calories?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["strollHistory"]>

export type StrollHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  visitedPlaceId?: boolean
  placeName?: boolean
  visitedAt?: boolean
  strollTime?: boolean
  meter?: boolean
  steps?: boolean
  calories?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["strollHistory"]>

export type StrollHistorySelectScalar = {
  id?: boolean
  userId?: boolean
  visitedPlaceId?: boolean
  placeName?: boolean
  visitedAt?: boolean
  strollTime?: boolean
  meter?: boolean
  steps?: boolean
  calories?: boolean
}

export type StrollHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "visitedPlaceId" | "placeName" | "visitedAt" | "strollTime" | "meter" | "steps" | "calories", ExtArgs["result"]["strollHistory"]>
export type StrollHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  pictures?: boolean | Prisma.StrollHistory$picturesArgs<ExtArgs>
  categories?: boolean | Prisma.StrollHistory$categoriesArgs<ExtArgs>
  _count?: boolean | Prisma.StrollHistoryCountOutputTypeDefaultArgs<ExtArgs>
}
export type StrollHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type StrollHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $StrollHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StrollHistory"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    pictures: Prisma.$PicturePayload<ExtArgs>[]
    categories: Prisma.$StrollHistoryCategoryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    visitedPlaceId: string
    placeName: string | null
    visitedAt: Date
    strollTime: number
    meter: number
    steps: number
    calories: runtime.Decimal
  }, ExtArgs["result"]["strollHistory"]>
  composites: {}
}

export type StrollHistoryGetPayload<S extends boolean | null | undefined | StrollHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload, S>

export type StrollHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StrollHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StrollHistoryCountAggregateInputType | true
  }

export interface StrollHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StrollHistory'], meta: { name: 'StrollHistory' } }
  /**
   * Find zero or one StrollHistory that matches the filter.
   * @param {StrollHistoryFindUniqueArgs} args - Arguments to find a StrollHistory
   * @example
   * // Get one StrollHistory
   * const strollHistory = await prisma.strollHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StrollHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, StrollHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StrollHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StrollHistoryFindUniqueOrThrowArgs} args - Arguments to find a StrollHistory
   * @example
   * // Get one StrollHistory
   * const strollHistory = await prisma.strollHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StrollHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StrollHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StrollHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryFindFirstArgs} args - Arguments to find a StrollHistory
   * @example
   * // Get one StrollHistory
   * const strollHistory = await prisma.strollHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StrollHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, StrollHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StrollHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryFindFirstOrThrowArgs} args - Arguments to find a StrollHistory
   * @example
   * // Get one StrollHistory
   * const strollHistory = await prisma.strollHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StrollHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StrollHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StrollHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StrollHistories
   * const strollHistories = await prisma.strollHistory.findMany()
   * 
   * // Get first 10 StrollHistories
   * const strollHistories = await prisma.strollHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const strollHistoryWithIdOnly = await prisma.strollHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StrollHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, StrollHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StrollHistory.
   * @param {StrollHistoryCreateArgs} args - Arguments to create a StrollHistory.
   * @example
   * // Create one StrollHistory
   * const StrollHistory = await prisma.strollHistory.create({
   *   data: {
   *     // ... data to create a StrollHistory
   *   }
   * })
   * 
   */
  create<T extends StrollHistoryCreateArgs>(args: Prisma.SelectSubset<T, StrollHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StrollHistories.
   * @param {StrollHistoryCreateManyArgs} args - Arguments to create many StrollHistories.
   * @example
   * // Create many StrollHistories
   * const strollHistory = await prisma.strollHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StrollHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, StrollHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StrollHistories and returns the data saved in the database.
   * @param {StrollHistoryCreateManyAndReturnArgs} args - Arguments to create many StrollHistories.
   * @example
   * // Create many StrollHistories
   * const strollHistory = await prisma.strollHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StrollHistories and only return the `id`
   * const strollHistoryWithIdOnly = await prisma.strollHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StrollHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StrollHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StrollHistory.
   * @param {StrollHistoryDeleteArgs} args - Arguments to delete one StrollHistory.
   * @example
   * // Delete one StrollHistory
   * const StrollHistory = await prisma.strollHistory.delete({
   *   where: {
   *     // ... filter to delete one StrollHistory
   *   }
   * })
   * 
   */
  delete<T extends StrollHistoryDeleteArgs>(args: Prisma.SelectSubset<T, StrollHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StrollHistory.
   * @param {StrollHistoryUpdateArgs} args - Arguments to update one StrollHistory.
   * @example
   * // Update one StrollHistory
   * const strollHistory = await prisma.strollHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StrollHistoryUpdateArgs>(args: Prisma.SelectSubset<T, StrollHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StrollHistories.
   * @param {StrollHistoryDeleteManyArgs} args - Arguments to filter StrollHistories to delete.
   * @example
   * // Delete a few StrollHistories
   * const { count } = await prisma.strollHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StrollHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, StrollHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StrollHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StrollHistories
   * const strollHistory = await prisma.strollHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StrollHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, StrollHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StrollHistories and returns the data updated in the database.
   * @param {StrollHistoryUpdateManyAndReturnArgs} args - Arguments to update many StrollHistories.
   * @example
   * // Update many StrollHistories
   * const strollHistory = await prisma.strollHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StrollHistories and only return the `id`
   * const strollHistoryWithIdOnly = await prisma.strollHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StrollHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StrollHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StrollHistory.
   * @param {StrollHistoryUpsertArgs} args - Arguments to update or create a StrollHistory.
   * @example
   * // Update or create a StrollHistory
   * const strollHistory = await prisma.strollHistory.upsert({
   *   create: {
   *     // ... data to create a StrollHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StrollHistory we want to update
   *   }
   * })
   */
  upsert<T extends StrollHistoryUpsertArgs>(args: Prisma.SelectSubset<T, StrollHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__StrollHistoryClient<runtime.Types.Result.GetResult<Prisma.$StrollHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StrollHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryCountArgs} args - Arguments to filter StrollHistories to count.
   * @example
   * // Count the number of StrollHistories
   * const count = await prisma.strollHistory.count({
   *   where: {
   *     // ... the filter for the StrollHistories we want to count
   *   }
   * })
  **/
  count<T extends StrollHistoryCountArgs>(
    args?: Prisma.Subset<T, StrollHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StrollHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StrollHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StrollHistoryAggregateArgs>(args: Prisma.Subset<T, StrollHistoryAggregateArgs>): Prisma.PrismaPromise<GetStrollHistoryAggregateType<T>>

  /**
   * Group by StrollHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StrollHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StrollHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StrollHistoryGroupByArgs['orderBy'] }
      : { orderBy?: StrollHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StrollHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStrollHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StrollHistory model
 */
readonly fields: StrollHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StrollHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StrollHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  pictures<T extends Prisma.StrollHistory$picturesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StrollHistory$picturesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  categories<T extends Prisma.StrollHistory$categoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StrollHistory$categoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StrollHistoryCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StrollHistory model
 */
export interface StrollHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"StrollHistory", 'String'>
  readonly userId: Prisma.FieldRef<"StrollHistory", 'String'>
  readonly visitedPlaceId: Prisma.FieldRef<"StrollHistory", 'String'>
  readonly placeName: Prisma.FieldRef<"StrollHistory", 'String'>
  readonly visitedAt: Prisma.FieldRef<"StrollHistory", 'DateTime'>
  readonly strollTime: Prisma.FieldRef<"StrollHistory", 'Int'>
  readonly meter: Prisma.FieldRef<"StrollHistory", 'Int'>
  readonly steps: Prisma.FieldRef<"StrollHistory", 'Int'>
  readonly calories: Prisma.FieldRef<"StrollHistory", 'Decimal'>
}
    

// Custom InputTypes
/**
 * StrollHistory findUnique
 */
export type StrollHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistory to fetch.
   */
  where: Prisma.StrollHistoryWhereUniqueInput
}

/**
 * StrollHistory findUniqueOrThrow
 */
export type StrollHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistory to fetch.
   */
  where: Prisma.StrollHistoryWhereUniqueInput
}

/**
 * StrollHistory findFirst
 */
export type StrollHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistory to fetch.
   */
  where?: Prisma.StrollHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StrollHistories to fetch.
   */
  orderBy?: Prisma.StrollHistoryOrderByWithRelationInput | Prisma.StrollHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StrollHistories.
   */
  cursor?: Prisma.StrollHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StrollHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StrollHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StrollHistories.
   */
  distinct?: Prisma.StrollHistoryScalarFieldEnum | Prisma.StrollHistoryScalarFieldEnum[]
}

/**
 * StrollHistory findFirstOrThrow
 */
export type StrollHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistory to fetch.
   */
  where?: Prisma.StrollHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StrollHistories to fetch.
   */
  orderBy?: Prisma.StrollHistoryOrderByWithRelationInput | Prisma.StrollHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StrollHistories.
   */
  cursor?: Prisma.StrollHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StrollHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StrollHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StrollHistories.
   */
  distinct?: Prisma.StrollHistoryScalarFieldEnum | Prisma.StrollHistoryScalarFieldEnum[]
}

/**
 * StrollHistory findMany
 */
export type StrollHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * Filter, which StrollHistories to fetch.
   */
  where?: Prisma.StrollHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StrollHistories to fetch.
   */
  orderBy?: Prisma.StrollHistoryOrderByWithRelationInput | Prisma.StrollHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StrollHistories.
   */
  cursor?: Prisma.StrollHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StrollHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StrollHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StrollHistories.
   */
  distinct?: Prisma.StrollHistoryScalarFieldEnum | Prisma.StrollHistoryScalarFieldEnum[]
}

/**
 * StrollHistory create
 */
export type StrollHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a StrollHistory.
   */
  data: Prisma.XOR<Prisma.StrollHistoryCreateInput, Prisma.StrollHistoryUncheckedCreateInput>
}

/**
 * StrollHistory createMany
 */
export type StrollHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StrollHistories.
   */
  data: Prisma.StrollHistoryCreateManyInput | Prisma.StrollHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StrollHistory createManyAndReturn
 */
export type StrollHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many StrollHistories.
   */
  data: Prisma.StrollHistoryCreateManyInput | Prisma.StrollHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StrollHistory update
 */
export type StrollHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a StrollHistory.
   */
  data: Prisma.XOR<Prisma.StrollHistoryUpdateInput, Prisma.StrollHistoryUncheckedUpdateInput>
  /**
   * Choose, which StrollHistory to update.
   */
  where: Prisma.StrollHistoryWhereUniqueInput
}

/**
 * StrollHistory updateMany
 */
export type StrollHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StrollHistories.
   */
  data: Prisma.XOR<Prisma.StrollHistoryUpdateManyMutationInput, Prisma.StrollHistoryUncheckedUpdateManyInput>
  /**
   * Filter which StrollHistories to update
   */
  where?: Prisma.StrollHistoryWhereInput
  /**
   * Limit how many StrollHistories to update.
   */
  limit?: number
}

/**
 * StrollHistory updateManyAndReturn
 */
export type StrollHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * The data used to update StrollHistories.
   */
  data: Prisma.XOR<Prisma.StrollHistoryUpdateManyMutationInput, Prisma.StrollHistoryUncheckedUpdateManyInput>
  /**
   * Filter which StrollHistories to update
   */
  where?: Prisma.StrollHistoryWhereInput
  /**
   * Limit how many StrollHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StrollHistory upsert
 */
export type StrollHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the StrollHistory to update in case it exists.
   */
  where: Prisma.StrollHistoryWhereUniqueInput
  /**
   * In case the StrollHistory found by the `where` argument doesn't exist, create a new StrollHistory with this data.
   */
  create: Prisma.XOR<Prisma.StrollHistoryCreateInput, Prisma.StrollHistoryUncheckedCreateInput>
  /**
   * In case the StrollHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StrollHistoryUpdateInput, Prisma.StrollHistoryUncheckedUpdateInput>
}

/**
 * StrollHistory delete
 */
export type StrollHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
  /**
   * Filter which StrollHistory to delete.
   */
  where: Prisma.StrollHistoryWhereUniqueInput
}

/**
 * StrollHistory deleteMany
 */
export type StrollHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StrollHistories to delete
   */
  where?: Prisma.StrollHistoryWhereInput
  /**
   * Limit how many StrollHistories to delete.
   */
  limit?: number
}

/**
 * StrollHistory.pictures
 */
export type StrollHistory$picturesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  where?: Prisma.PictureWhereInput
  orderBy?: Prisma.PictureOrderByWithRelationInput | Prisma.PictureOrderByWithRelationInput[]
  cursor?: Prisma.PictureWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PictureScalarFieldEnum | Prisma.PictureScalarFieldEnum[]
}

/**
 * StrollHistory.categories
 */
export type StrollHistory$categoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistoryCategory
   */
  select?: Prisma.StrollHistoryCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistoryCategory
   */
  omit?: Prisma.StrollHistoryCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryCategoryInclude<ExtArgs> | null
  where?: Prisma.StrollHistoryCategoryWhereInput
  orderBy?: Prisma.StrollHistoryCategoryOrderByWithRelationInput | Prisma.StrollHistoryCategoryOrderByWithRelationInput[]
  cursor?: Prisma.StrollHistoryCategoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StrollHistoryCategoryScalarFieldEnum | Prisma.StrollHistoryCategoryScalarFieldEnum[]
}

/**
 * StrollHistory without action
 */
export type StrollHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StrollHistory
   */
  select?: Prisma.StrollHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StrollHistory
   */
  omit?: Prisma.StrollHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrollHistoryInclude<ExtArgs> | null
}
