/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サインインページ */
        get: operations["getSignIn"];
        put?: never;
        /** Credentialsでサインイン */
        post: operations["signInUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** セッション情報を取得 */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** サインアウト */
        post: operations["signOutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth プロバイダーのコールバック */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザー登録 */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** ユーザー情報を更新 */
        put: operations["updateUser"];
        post?: never;
        /** ユーザーを削除 */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-stroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 散歩条件から目的地候補を検索 */
        post: operations["searchStroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 散歩履歴一覧を取得 */
        get: operations["getHistories"];
        put?: never;
        /** 散歩履歴を登録 */
        post: operations["createHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{historyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 散歩履歴を個別取得 */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        /** 散歩履歴を削除 */
        delete: operations["deleteHistory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 画像を登録 */
        post: operations["createImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 画像を個別取得 */
        get: operations["getImage"];
        put?: never;
        post?: never;
        /** 画像を削除 */
        delete: operations["deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignInPayload: {
            /**
             * Format: email
             * @description メールアドレス
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @description パスワード
             * @example plain-text-password
             */
            password: string;
        };
        RegisterPayload: {
            /**
             * Format: email
             * @description メールアドレス
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @description パスワード（8文字以上）
             * @example plain-text-password
             */
            password: string;
        };
        RegisterResponse: {
            /**
             * @description 作成されたユーザーのID
             * @example 1
             */
            id: string;
        };
        UpdateUserPayload: {
            /**
             * Format: email
             * @description メールアドレス
             * @example user@example.com
             */
            email?: string;
            /**
             * Format: password
             * @description 新しいパスワード
             * @example new-password
             */
            password?: string;
        };
        SessionResponse: {
            user?: {
                /**
                 * @description ユーザーID
                 * @example user-123
                 */
                id?: string;
                /**
                 * Format: email
                 * @description メールアドレス
                 * @example user@example.com
                 */
                email?: string;
            };
            /**
             * Format: date-time
             * @description セッション有効期限
             * @example 2025-03-20T12:00:00Z
             */
            expires?: string;
        };
        SearchStrollPayload: {
            /**
             * @description 現在地の緯度
             * @example 35.681236
             */
            latitude: number;
            /**
             * @description 現在地の経度
             * @example 139.767125
             */
            longitude: number;
            /**
             * @description 目的地のカテゴリ
             * @example 公園
             */
            categories: string;
            /**
             * @description 散歩可能時間
             * @example 60
             */
            duration: number;
        };
        SearchStrollResponse: {
            /**
             * @description Google Places APIの目的地ID
             * @example ChIJ123456789
             */
            placeId: string;
            /**
             * @description 目的地名
             * @example 新宿御苑
             */
            name: string;
            /**
             * @description 現在地から目的地までの距離（メートル）
             * @example 2500
             */
            meter: number;
            /**
             * @description 現在地から目的地までの予定所要時間
             * @example 35
             */
            scheduledTime: number;
        };
        CreateHistoryPayload: {
            /**
             * @description Google Places APIの目的地ID
             * @example ChIJ123456789
             */
            placeId: string;
            /**
             * @description 目的地のカテゴリ
             * @example 公園
             */
            categories: string;
            /**
             * @description 散歩にかかった時間
             * @example 45.5
             */
            timeTaken: number;
            /**
             * @description 散歩した距離（メートル）
             * @example 3200
             */
            meter: number;
            /**
             * @description 歩数
             * @example 4200
             */
            steps: number;
            /**
             * @description 消費カロリー
             * @example 180.5
             */
            calories: number;
            /**
             * Format: date-time
             * @description 散歩履歴の登録日時
             * @example 2026-08-19T10:30:00Z
             */
            createdAt?: string;
        };
        HistoryResponse: {
            /**
             * @description 散歩履歴のID
             * @example history-001
             */
            historyId: string;
            /**
             * @description Google Places APIの目的地ID
             * @example ChIJ123456789
             */
            placeId: string;
            /**
             * @description 目的地のカテゴリ
             * @example 公園
             */
            categories: string;
            /**
             * @description 散歩にかかった時間
             * @example 45.5
             */
            timeTaken: number;
            /**
             * @description 散歩した距離（メートル）
             * @example 3200
             */
            meter: number;
            /**
             * @description 歩数
             * @example 4200
             */
            steps: number;
            /**
             * @description 消費カロリー
             * @example 180.5
             */
            calories: number;
            /**
             * Format: date-time
             * @description 散歩履歴の登録日時
             * @example 2026-08-19T10:30:00Z
             */
            createdAt: string;
            /**
             * @description 散歩履歴に紐づく画像パスの一覧
             * @example [
             *       "/images/history-001/image-001.jpg",
             *       "/images/history-001/image-002.jpg"
             *     ]
             */
            imagePaths: string[];
        };
        CreateImagePayload: {
            /**
             * @description 画像のID
             * @example image-001
             */
            imageId: string;
            /**
             * @description 画像が紐づく散歩履歴のID
             * @example history-001
             */
            historyId: string;
        };
        ImageResponse: {
            /**
             * @description 画像のID
             * @example image-001
             */
            imageId: string;
            /**
             * @description 画像が紐づく散歩履歴のID
             * @example history-001
             */
            historyId: string;
        };
    };
    responses: {
        /** @description 予期しないエラー */
        UnexpectedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example unexpected_error_occurred */
                    message?: string;
                };
            };
        };
        /** @description 不正なリクエスト */
        InvalidError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example invalid_input */
                    message?: string;
                };
            };
        };
        /** @description 認証されてないユーザのリクエスト */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example authentication_required */
                    message?: string;
                };
            };
        };
        /** @description 既存リソースの登録リクエスト */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example resource_already_exists */
                    message?: string;
                };
            };
        };
        /** @description リソースが見つからない */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example not_found */
                    message?: string;
                };
            };
        };
    };
    parameters: {
        /** @description 散歩履歴のID */
        HistoryIdParam: string;
        /** @description 画像のID */
        ImageIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description サインインフォームを取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    signInUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInPayload"];
            };
        };
        responses: {
            /** @description サインイン成功、セッションが作成される */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セッション情報の取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    signOutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description サインアウト成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    authCallback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "github";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description リダイレクト */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPayload"];
            };
        };
        responses: {
            /** @description 登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserPayload"];
            };
        };
        responses: {
            /** @description ユーザー情報の更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            401: components["responses"]["UnauthorizedError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザーの削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    searchStroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchStrollPayload"];
            };
        };
        responses: {
            /** @description 目的地候補の検索成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchStrollResponse"][];
                };
            };
            400: components["responses"]["InvalidError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getHistories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 散歩履歴一覧の取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    createHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHistoryPayload"];
            };
        };
        responses: {
            /** @description 散歩履歴の登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 散歩履歴のID */
                historyId: components["parameters"]["HistoryIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 散歩履歴の取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    deleteHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 散歩履歴のID */
                historyId: components["parameters"]["HistoryIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 散歩履歴の削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    createImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImagePayload"];
            };
        };
        responses: {
            /** @description 画像の登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 画像のID */
                imageId: components["parameters"]["ImageIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 画像情報の取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 画像のID */
                imageId: components["parameters"]["ImageIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 画像の削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
}
