/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サインインページ */
        get: operations["getSignIn"];
        put?: never;
        /** Credentialsでサインイン */
        post: operations["signInUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** セッション情報を取得 */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** サインアウト */
        post: operations["signOutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth プロバイダーのコールバック */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザー登録 */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** ユーザー情報を更新 */
        put: operations["updateUser"];
        post?: never;
        /** ユーザーを削除 */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-stroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 散歩条件から目的地候補を検索 */
        post: operations["searchStroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 徒歩ルート地図を表示 */
        get: operations["getWalkingMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 散歩履歴一覧を取得 */
        get: operations["getHistories"];
        put?: never;
        /** 散歩履歴を登録 */
        post: operations["createHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{historyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 散歩履歴を個別取得 */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        /** 散歩履歴を削除 */
        delete: operations["deleteHistory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 画像を登録 */
        post: operations["createImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 画像を削除 */
        delete: operations["deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignInPayload: {
            /**
             * Format: email
             * @description メールアドレス
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @description パスワード
             * @example plain-text-password
             */
            password: string;
        };
        RegisterPayload: {
            /**
             * Format: email
             * @description メールアドレス
             * @example user@example.com
             */
            email: string;
            /**
             * @description ユーザー名
             * @example さんぽ太郎
             */
            username: string;
            /**
             * Format: password
             * @description パスワード（8文字以上）
             * @example plain-text-password
             */
            password: string;
        };
        RegisterResponse: {
            /**
             * @description 作成されたユーザーのID
             * @example 1
             */
            id: string;
        };
        UpdateUserPayload: {
            /**
             * Format: email
             * @description メールアドレス
             * @example user@example.com
             */
            email?: string;
            /**
             * Format: password
             * @description 新しいパスワード
             * @example new-password
             */
            password?: string;
        };
        SessionResponse: {
            user?: {
                /**
                 * @description ユーザーID
                 * @example user-123
                 */
                id?: string;
                /**
                 * Format: email
                 * @description メールアドレス
                 * @example user@example.com
                 */
                email?: string;
            };
            /**
             * Format: date-time
             * @description セッション有効期限
             * @example 2025-03-20T12:00:00Z
             */
            expires?: string;
        };
        SearchStrollPayload: {
            /**
             * @description 現在地の緯度
             * @example 35.681236
             */
            latitude: number;
            /**
             * @description 現在地の経度
             * @example 139.767125
             */
            longitude: number;
            /**
             * @description 目的地のカテゴリ（複数指定する場合はカンマ区切り）
             * @example 公園
             */
            categories: string;
            /**
             * @description 散歩可能時間
             * @example 60
             */
            duration: number;
        };
        SearchStrollResponse: {
            /**
             * @description Google Places APIの目的地ID
             * @example ChIJ123456789
             */
            placeId: string;
            /**
             * @description 目的地名
             * @example 新宿御苑
             */
            name: string;
            /**
             * @description 現在地から目的地までの距離（メートル）
             * @example 2500
             */
            meter: number;
            /**
             * @description 現在地から目的地までの予定所要時間
             * @example 35
             */
            scheduledTime: number;
            /**
             * @description 目的地の緯度
             * @example 35.689634
             */
            latitude: number;
            /**
             * @description 目的地の経度
             * @example 139.692101
             */
            longitude: number;
        };
        CreateHistoryPayload: {
            /**
             * @description Google Places APIの目的地ID
             * @example ChIJ123456789
             */
            placeId: string;
            /**
             * @description 検索結果で取得した目的地名
             * @example 木場公園
             */
            placeName: string;
            /**
             * @description 目的地のカテゴリ
             * @example 公園
             */
            categories: string;
            /**
             * @description 散歩にかかった時間
             * @example 45.5
             */
            timeTaken: number;
            /**
             * @description 散歩した距離（メートル）
             * @example 3200
             */
            meter: number;
            /**
             * @description 歩数
             * @example 4200
             */
            steps: number;
            /**
             * @description 消費カロリー
             * @example 180.5
             */
            calories: number;
            /**
             * Format: date-time
             * @description 散歩履歴の登録日時
             * @example 2026-08-19T10:30:00Z
             */
            createdAt?: string;
        };
        HistoryResponse: {
            /**
             * @description 散歩履歴のID
             * @example history-001
             */
            historyId: string;
            /**
             * @description Google Places APIの目的地ID
             * @example ChIJ123456789
             */
            placeId: string;
            /**
             * @description 保存済みの目的地名。旧データなど未保存の場合は空文字
             * @example 木場公園
             */
            placeName: string;
            /**
             * @description 目的地のカテゴリ
             * @example 公園
             */
            categories: string;
            /**
             * @description 散歩にかかった時間
             * @example 45.5
             */
            timeTaken: number;
            /**
             * @description 散歩した距離（メートル）
             * @example 3200
             */
            meter: number;
            /**
             * @description 歩数
             * @example 4200
             */
            steps: number;
            /**
             * @description 消費カロリー
             * @example 180.5
             */
            calories: number;
            /**
             * Format: date-time
             * @description 散歩履歴の登録日時
             * @example 2026-08-19T10:30:00Z
             */
            createdAt: string;
            /**
             * @description 散歩履歴に紐づく画像の参照パス一覧。画像の取得はこのフィールドで行い、
             *     画像取得用の個別APIは設けない。
             *     画像ファイルを直接指すため、そのまま img の src に指定できる。
             *     開発環境では /images 配下の静的パス、本番環境ではオブジェクトストレージのURL。
             * @example [
             *       "/images/history-001/9f2c1a4e-6b3d-4c8a-91f2-0a7e5d3b1c4f.jpg",
             *       "/images/history-001/3d81b7c0-52ea-4f19-8b6d-7c2a9e4f0d15.jpg"
             *     ]
             */
            imagePaths: string[];
        };
        CreateImagePayload: {
            /**
             * @description 画像が紐づく散歩履歴のID
             * @example history-001
             */
            historyId: string;
            /**
             * Format: binary
             * @description 画像ファイル本体。対応形式は image/jpeg・image/png・image/webp、
             *     最大5MB。画像のIDはサーバー側で採番する。
             */
            file: string;
        };
        ImageResponse: {
            /**
             * @description 画像のID
             * @example image-001
             */
            imageId: string;
            /**
             * @description 画像が紐づく散歩履歴のID
             * @example history-001
             */
            historyId: string;
            /**
             * @description 画像ファイルの参照パス。HistoryResponse.imagePaths と同じ形式。
             *     開発環境では /images 配下の静的パス、本番環境ではオブジェクトストレージのURL。
             * @example /images/history-001/9f2c1a4e-6b3d-4c8a-91f2-0a7e5d3b1c4f.jpg
             */
            imagePath: string;
        };
    };
    responses: {
        /** @description 予期しないエラー */
        UnexpectedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example unexpected_error_occurred */
                    message?: string;
                };
            };
        };
        /** @description 不正なリクエスト */
        InvalidError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example invalid_input */
                    message?: string;
                };
            };
        };
        /** @description 認証されてないユーザのリクエスト */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example authentication_required */
                    message?: string;
                };
            };
        };
        /** @description 既存リソースの登録リクエスト */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example resource_already_exists */
                    message?: string;
                };
            };
        };
        /** @description リソースが見つからない */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example not_found */
                    message?: string;
                };
            };
        };
    };
    parameters: {
        /** @description 散歩履歴のID */
        HistoryIdParam: string;
        /** @description 画像のID */
        ImageIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description サインインフォームを取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    signInUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInPayload"];
            };
        };
        responses: {
            /** @description サインイン成功、セッションが作成される */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セッション情報の取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    signOutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description サインアウト成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    authCallback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "github";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description リダイレクト */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPayload"];
            };
        };
        responses: {
            /** @description 登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserPayload"];
            };
        };
        responses: {
            /** @description ユーザー情報の更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            401: components["responses"]["UnauthorizedError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザーの削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    searchStroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchStrollPayload"];
            };
        };
        responses: {
            /** @description 目的地候補の検索成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchStrollResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getWalkingMap: {
        parameters: {
            query: {
                /**
                 * @description 現在地の緯度
                 * @example 35.681236
                 */
                originLat: number;
                /**
                 * @description 現在地の経度
                 * @example 139.767125
                 */
                originLng: number;
                /**
                 * @description 目的地の緯度
                 * @example 35.689634
                 */
                destinationLat: number;
                /**
                 * @description 目的地の経度
                 * @example 139.692101
                 */
                destinationLng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Google Maps Embed API の徒歩ルート地図へリダイレクト */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 座標または地図用 API キーが不正・未設定 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example map_unavailable */
                        message?: string;
                    };
                };
            };
        };
    };
    getHistories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 散歩履歴一覧の取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    createHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHistoryPayload"];
            };
        };
        responses: {
            /** @description 散歩履歴の登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 散歩履歴のID */
                historyId: components["parameters"]["HistoryIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 散歩履歴の取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    deleteHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 散歩履歴のID */
                historyId: components["parameters"]["HistoryIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 散歩履歴の削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    createImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateImagePayload"];
            };
        };
        responses: {
            /** @description 画像の登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            400: components["responses"]["InvalidError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 画像のID */
                imageId: components["parameters"]["ImageIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 画像の削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
}
